blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homePage
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homePage, name='homepage'),
    path('blogs/', include('blog_app.urls')),
    path('users/', include('users.urls')),
]

blog_app/urls.py
from django.urls import path
from .views import *
app_name ='blog'
urlpatterns = [
    path('posts/',posts_view, name='posts'),
    path('posts/<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name="post_detail"),
    path('posts/comment/', Post_Comment.as_view(), name="post_comment"),
    
]

users/urls.py
from django.urls import path
from .views import *

app_name ='users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils  import timezone
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Post.Status.PUBLISHED)
    
    
class Post(models.Model):
    
    class Status(models.TextChoices):
        PUBLISHED = 'PB', 'Published'
        DRAFT = "DF", 'Draft'
        
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT)
    
    objects = models.Manager()
    published = PublishedManager()
    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']),]
        
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                  self.publish.month,
                                                  self.publish.day,
                                                  self.slug])
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
    
    def __str__(self):
        return f"Comment by {self.user} on {self.post}"

users/models.py
from django.db import models

# Create your models here.

blog_app/forms.py
from django  import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

users/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

        
    

blog/views.py
from django.shortcuts import render
from blog_app.models import Post
def homePage(request):
    
    return render(request, 'index.html' )

blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage
from .forms import CommentForm
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
@login_required(login_url='users:login')
def posts_view(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list,3)
    page_number = request.GET.get('page',1)
    posts = paginator.get_page(page_number)
    context= {
        'posts':posts,
    }
    return render(request, 'blog/posts.html', context )

@login_required(login_url='users:login')
def post_detail(request,year,month,day,post):
    
    comment_form = CommentForm()
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day = day)
    comments  = post.comments.filter(active=True)
    context = {
        'post':post,
        'comments':comments,
        'comment_form':comment_form
    }
    return render(request,'blog/post_detail.html', context)






@method_decorator(login_required(login_url='users:login'), name='dispatch')
class Post_Comment(View):
    def post(self,request):
        form = CommentForm(request.POST)
        post_id = request.POST.get('post_id')
        path_url = request.POST.get('path_url')
        post = get_object_or_404(Post, id=post_id,status=Post.Status.PUBLISHED)
        comment = None
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
        return redirect(path_url)
    
        
        # return render(request, 'blog/comment.html', {
        #     'post':post,
        #     'form':form,
        #     'comment':comment
        # })

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
# Create your views here.

class LoginView(View):
    def get(self,request):
        login_form = LoginForm
        context = {
            'login_form':login_form
        }
        return render(request,'users/login.html', context)
    
    
    def post(self,request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('homepage')
                
            else:
                form.add_error(None,'fudsfgisudgb')
            
        return render(request, 'users/login.html', {'form':form})
    
    
class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect('homepage')
        

blog_app/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %}{{post.title}}{% endblock title %}
{% block content %}

<div class="container mt-5">
    <div class="card p-5 ">
        
        <h2 class="fs-1 text-center">post title: <span class='badge bg-primary'>{{post.title}}</span></h2>
        
        <h3 class="text-center">Post author <span class="badge bg-success">{{post.author}}</span> </h3>
        <h3 class="text-center">Post author <span class="badge bg-dark-subtle text-dark">{{post.publish}}</span> </h3>
        <div class="fs-2 bg-light border border-1 rounded p-5">
            <p class=" badge bg-secondary ">post body</p>
            <p class="fs-3">{{post.body}}</p>
            
        </div>
        <div class="comments-box col-10 me-auto">
            <div class="comment-list card m-1 p-5">
                <h2>Comments to this post</h2>
                {% for comment in comments %}
                    <div class="comment-container border border-1 bg-warning rounded m-2 p-3">
                        <h2 class="text-decoration-underline fs-6">{{comment.user.username}} <span class="badge text-primary">{{comment.created}}</span></h2>
                        <p class="fs-4">{{comment.body}}</p>
                    </div>

                {% endfor %}
            </div>
            <div class="comment-form">
                <form method="post" action="{% url 'blog:post_comment' %}" class="form" >
                    {% csrf_token %}
                    <input type='hidden' value={{post.id}} name='post_id'>
                    <input type='hidden' value={{request.path}} name='path_url'>
                    {{comment_form.as_p}}
                    <button type="submit" class="btn btn-primary">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

blog_app/templates/blog/posts.html
{% extends "base.html" %}
{% block title %}All posts page{% endblock title %}
{% block content %}
<div class="container">
    <h1 > all posts</h1>
    <div class="posts-container ">
        {% for post in posts %}
        <div class="card p-5 m-1 col-10 mx-auto">
            {% comment %} <a href="{% url 'blog:post_detail' post.id %}" class="fs-2 text-center" >{{post.title}}</a> {% endcomment %}
            <a href="{{post.get_absolute_url}}" class="fs-2 " >{{post.title}}</a>
            <p  class="fs-4 " > by <span  class="fs-4 fw-bold " >{{post.author}}</span> at {{post.publish}}</p>
            
        </div>
        {% endfor %}
        {% include "pagination.html" %}
    </div>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Main page{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class='bg-dark-subtle'>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container">
            <a class="navbar-brand fs-3" href="{% url 'homepage' %}">BAPP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:posts'   %}">Posts</a>
                    </li>
                
                </ul>
                <ul class="navbar-nav  mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Profile
                        </a>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        {% if request.user.is_authenticated %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'users:login' %}">Log in</a></li>
                        {% endif %}
                        </ul>
                    </li>
                </ul>
                
            </div>
            </div>
        </nav>

        {% block content %}{% endblock content %}
      
      
      
      
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
    

{% block content %}
    <div class="container mt-5">
        <h1>Welcome to BAPP <span class='text-decoration-underline'> Blog Application</span></h1>
        {% comment %} <a href="{% url 'blog:posts' %}">All posts</a> {% endcomment %}
    </div>
{% endblock content %}

templates/pagination.html
<nav class=" container col-10 d-flex justify-content-center">
    <ul class="pagination container col-3 mt-3 ">
      <li class="page-item">
        {% if posts.has_previous %}
            <a class='page-link' href="?page={{posts.previous_page_number}}">Previous</a>
        {% endif %}
        </li>
        <li class="page-item "><a class='page-link disabled'>Page {{posts.number}} of {{posts.paginator.num_pages}}</a></li>
        <li class="page-item">
            {% if posts.has_next %}
                <a class='page-link' href="?page={{posts.next_page_number}}">next</a>
            {% endif %}
        </li>
    </ul>
</nav>

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Login Form{% endblock title %}
    

{% block content %}
    <div class="login-container container">
        <form action="{% url 'users:login' %}" class="form" method="post">
            {% csrf_token %}
            {{login_form.as_p}}
            

            <button class="btn btn-primary" type="submit">Log In</button>
        </form>

    </div>
{% endblock content %}